name: Ess-message-consumer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 ./ess_message_consumer --ignore=E501,E203,E402,W503,Q000,W293,E731

    - name: Check formatting with black
      run: |
        black --check ./ess_message_consumer

    - name: Check imports with isort
      run: |
        isort ./ess_message_consumer/ --check-only --profile black -v

    - name: Test with pytest
      run: |
        pytest -v
